%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/imu_imu_t"
image0_topic: "/zed/zed_node/left_raw/image_raw_color/image_raw"
image1_topic: "/zed/zed_node/right_raw/image_raw_color/image_raw"
output_path: "/root/catkin_ws/src/VINS-Fusion/"

cam0_calib: "cam0.yaml"
cam1_calib: "cam1.yaml"
image_width: 1280
image_height: 720
   
# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.01152904, -0.91297258, -0.40785801, -0.04958088,
          -0.99947839,  0.02282702, -0.02284474,  0.0635034 ,
           0.0301668 ,  0.40738189, -0.91275953, -0.13499348,
           0.0,  0.0,  0.0,  1.0]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.01947147, -0.91157922, -0.41066312, -0.05210137,
          -0.99969785,  0.02391432, -0.005684  , -0.0551954,
           0.01500215,  0.41042836, -0.91176943, -0.13371907,
           0.        ,  0.        ,  0.        ,  1.        ]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 200            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 0                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
#acc_n: 0.0017          # accelerometer measurement noise standard deviation.
#gyr_n: 8.2739         # gyroscope measurement noise standard deviation.
#acc_w: 0.0057        # accelerometer bias random work noise standard deviation.
#gyr_w: 8.7367       # gyroscope bias random work noise standard deviation.
acc_n: 0.19366268769180487          # accelerometer measurement noise standard deviation. 
gyr_n: 0.011292103054687074         # gyroscope measurement noise standard deviation.     
acc_w: 0.020702566216083702        # accelerometer bias random work noise standard deviation.  
gyr_w: 3.6132794408280443e-03       # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 1                     # online estimate time offset between camera and imu
td: -0.01                           # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/root/catkin_ws/src/VINS-Fusion/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
